services:
  invoice:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: .env

  browserless:
    image: ghcr.io/browserless/chromium
    ports:
      - 3333:3000
    restart: unless-stopped
    environment:
      CONCURRENT: 5
      TOKEN: ${BROWSERLESS_TOKEN}
