version: "3.7"
services:
  pg:
    image: docker.io/postgres:16
    hostname: pg
    container_name: pg
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "invoice"

volumes:
  db_data:
