services:
  invoice:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: .env
    environment:
      PUBLIC_ORIGIN: ${PUBLIC_ORIGIN:-http://localhost:3000}
      ORIGIN: ${ORIGIN:-http://localhost:3000}
      CHROMIUM_PATH: /usr/bin/chromium-browser
