#:schema node_modules/wrangler/config-schema.json
name = "invoice"
account_id = "4898a4ed01a57e0107e69ce4695b8ab1"
compatibility_date = "2024-07-29"
# pages_build_output_dir = ".svelte-kit/cloudflare"

main = "./build/handler.js"
build.command = "pnpm run build"


compatibility_flags = ["nodejs_compat"]

browser = { binding = "MYBROWSER" }
