name: Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: docker login

      - name: Build Docker image
        run: docker build . --tag ghcr.io/jacokok/invoice:latest

      - name: Docker Push
        run: docker push ghcr.io/jacokok/invoice:latest
